### ISSUE TITLE
String size problem

### ISSUE THREAD

**Issue by emilr256** [urbanze/emb_esp32_aes#1]
Hello!
This code works only if the bla String is smaller that 16 characters. Can't encode longer strings like:
String bla = "0123456789012345678901234567890123456789012345678901234567890123456789";

**Comment by urbanze** [comment]
it's correct! AES is a 16B block encryption, so to encrypt larger strings, you need to create a method that will break your "big string" into "smaller strings".

RC4 (Decrapted stream crypto, **main.ino**) have a "variable output size", test it.

**Comment by emilr256** [comment]
Hello!
Thank You for Your fast answer! As You mentioned, with RC4 works well, but RC4 is "insecure". At a moment, only AES is enough secure (maybe ECB is not the best, but at a moment is no public hack).
I still searching for an applicable long string (minimal 70 characters) encoder with AES CBC for ESP32, but there is no one useful example online!
If You have maybe a bit of time i will be wherry thankful for such an example, or modification of You example!

**Comment by urbanze** [comment]
[code.txt](https://github.com/urbanze/emb_esp32_aes/files/4022032/code.txt)

Try this (ECB) and tell me (I can't test with Arduino IDE, in IDF worked.). This code just crop string in 16B, crypt and do again.... With CBC, you need to do simillary, crop string in 16B and use last IV array to crypt new block. 

Note1: In CBC, MBEDTLS_CBC() will update IV array with new values (its correct, you need to use this new IV and not the initial IV), see docs.

Note2: I changed String bla to char bla[], caution.

**Comment by emilr256** [comment]
Hello!
I have tested the ECB version and it works well on ESP32 WROOM. Maybe You can commit the changes to Your main code. 
Unfortunately the CBC version still not works with this, but this will be most important because there is at moment no one working CBC AES example with longer encryption that 16 char.

**Comment by urbanze** [comment]
This code need some modifications to work with CBC (like last IV array), but is the same thing, break string in 16B over and over... I will commit ECB/CBC >16B capabillity.

**Comment by urbanze** [comment]
I push new commits with ECB/CBC >16B support (ac4b2a3). Please @emilr256 , test both codes and tell me (new issue) if anything goes wrong. Thanks!

**Comment by emilr256** [comment]
Hello!
OI have tested, but the encryption with 128 CBC is wrong on the beginning (first 16).
Please look at:
http://aes.online-domain-tools.com/run/?inputType=frm-text&text=c9%2095%2041%20fa%204e%208b%2044%20a0%2039%2069%20ed%20b2%201c%2098%2039%20aa%2039%20d7%2023%203e%20d6%2015%2064%2035%2011%2078%20e2%20fe%20d2%2040%208d%203f%20a7%2093%2079%2057%2060%20de%2026%20e5%20dd%2066%2091%2016%20f1%20e7%2055%2087%20ac%20ec%20f7%2036%20c6%2039%20b0%20a6%2071%20af%20f3%2056%2071%2037%20d6%20bb%2089%2080%2001%20a6%20de%204b%2064%209c%20a6%2041%2076%209b%2084%2007%2020%20fd&text_type=hex&function=aes&mode=cbc&key=31%2032%2033%2034%2035%2036%2037%2038%2039%2030%2031%2032%2033%2034%2035%2036&key_type=hex&iv=31%2032%2033%2034%2035%2036%2037%2038%2039%2030%2031%2032%2033%2034%2035%2036&do=form-submit&decrypt=do
The problem is just on first block.

**Comment by urbanze** [comment]
![Captura de tela de 2020-01-05 11-10-44](https://user-images.githubusercontent.com/29230962/71781320-13208480-2fac-11ea-84de-6fe840ce115b.png)
Here, encrypt works in both sides. Where did you get these hex numbers?

**Comment by emilr256** [comment]
I have try to decrypt.
https://ibb.co/HFktXSC

**Comment by emilr256** [comment]
The decryption still works on first output round, the errors happens on second and any next cipher.

**Comment by urbanze** [comment]
> I have try to decrypt.
> https://ibb.co/HFktXSC

I saw that it's wrong, but where did you get this chipertext (c9 95 41 fa...)? Show me how/where you get this chiper and all infos need (key, iv, etc)

**Comment by emilr256** [comment]
Here is a code:
mbedtls_aes_context aes;

unsigned char key[] = "1234567890123456";
unsigned char  iv[] = "1234567890123456";

char bla[] = "0123456789012345678901234567890123456789012345678901234567890123456789";
unsigned char out[16];
unsigned char inp[16];



void setup()
{
  Serial.begin(115200);

  mbedtls_aes_init(&aes);
  mbedtls_aes_setkey_enc(&aes, key, 128);
}

void loop()
{
    Serial.printf("\r\n\r\nPlaintext: ");
    Serial.printf("%s\n", bla);

    Serial.printf("Chipertext: ");
    for (int i = 0; i < strlen(bla); i += 16)
    {
        if (bla[i] == 0)
            {break;}
        
        memset(inp, 0, sizeof(inp));
        memset(out, 0, sizeof(out));

        for (int j = (0 + i); j < (16 + i); j++)
        {
            if (bla[j] != 0)
                {inp[j-i] = bla[j];}
            else
                {break;}
        }

        mbedtls_aes_crypt_cbc(&aes, MBEDTLS_AES_ENCRYPT, 16, iv, inp, out);
        
        for (int j = 0; j < 16; j++)
        {
           Serial.printf("%02x ", out[j]);
        }
    }

    delay(10000);
}

I read a serial:
https://ibb.co/x7vn2ff

The first chipertext is good, i can decrypt it:
https://ibb.co/84WvGtR

If i use a second (or any other chipertext) AFTER a first one is printed, for example a second chipertext (from the serial output of Arduino IDE) i receive an error:
https://ibb.co/NLKnZF2

On the web page, i use hex and not plain text, but HEX from 1234567890123456 is 31 32 33 34 35 36 37 38 39 30 31 32 33 34 35 36

The problem is on first block, all next blocks are OK, i have marked the problematical part and it happened after a first run, because the first run is OK, only a second run in loop produce this error.

**Comment by urbanze** [comment]
This occur because you are trying to decrypt the second crypt with first IV, you forgot that IV are updated by mbedtls. This is not bug, just your mistake.

To decrypt correctly the second time, you need to use the last IV (last 16B). Last IV is the last chipertext (e3 20 03 ea fb a4 33 14 8c c5 85 e5 b5 6f 2f 6f). So, will work nice. Check how CBC works!

Every encrypt (16B), mbedtls will update your IV[] with the bytes of the last chipertext (16B), so, to decrypt a new block, you need the last chipertext (last IV).

**Comment by emilr256** [comment]
You have right, i forgotten that it will change the IV. I am sorry, for trouble, will try to implement it now.
Well, at a moment this is the only one working example, so many tnx for Your time and work!

**Comment by urbanze** [comment]
Thanks for the discussion! Mbedtls supports hundreds of encryptions, it's cool to use it, especially with ESP32 hardware accelerator. Anything, new code or question, just ask!

**Comment by emilr256** [comment]
Mbedtlx is indeed the best. I have try for a while to find a solution for Atmel (Arduino) but it not works, also WolfSSL is not the best. ESP32 is ice because of hardware support for AES. For a first i have now a solution for encrypted communication. Will later try how it works on maple mini (STM32F103) and on a blue pill (also STM32F103 core). The last one have a price under a Arduino Nano, but with 32 bit CPU. Unfortunately, this series of STM32F103 don't support hardware acceleration for AES, but are cheap, well documented (have a feelig that is STM32 much better documented as ESP32) with a same footprint as a Nano.
